export const SHIPMENT_STATUS = {
  PENDING: 'PENDING',
  IN_TRANSIT: 'IN_TRANSIT',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  DELAYED: 'DELAYED',
  REGISTERED: 'REGISTERED',
  RETURNED: 'RETURNED',
}

export const TRACKING_STATUS_PROGRESS = {
  REGISTERED: 25,
  PENDING: 25,
  IN_TRANSIT: 50,
  OUT_FOR_DELIVERY: 75,
  DELIVERED: 100,
  CANCELLED: 0,
  DELAYED: 25,
  RETURNED: 0,
}

export const USER_ROLES = {
  ADMIN: 'Admin',
  OPERATOR: 'Operator',
  VIEWER: 'Viewer',
  ANALYST: 'Analyst',
}
